import { test, expect } from '@playwright/test'

test('真实账户：添加、编辑、服用、延后、跳过、历史、归档、重新登录', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: '登录 / 注册', exact: true }).click()
  await page.getByRole('button', { name: '免费注册', exact: true }).click()
  const email = `e2e-${Date.now()}@example.com`
  await page.getByLabel('你的称呼').fill('测试用户')
  await page.getByLabel('邮箱地址').fill(email)
  await page.getByLabel('密码', { exact: true }).fill('test-password-2026')
  await page.getByRole('button', { name: '创建账户', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByText('这一天，还没有服药计划')).toBeVisible()
  await page.getByRole('button', { name: '添加药品', exact: true }).click()
  await page.getByRole('button', { name: '手动填写' }).click()
  await page.getByLabel('药品名称').fill('界面验收药品')
  await page.getByLabel('药品规格').fill('测试规格 10 mg × 30片')
  await page.getByLabel('有效期至').fill('2030-12-31')
  await page.getByLabel('包装说明文字').fill('测试包装文字，仅用于软件验收。')
  await page.getByRole('button', { name: '设置提醒', exact: true }).click()
  await page.getByLabel('每次用量').fill('测试用量 1 片')
  await page.getByLabel('提醒时间 1', { exact: true }).fill('08:00')
  await page.getByRole('button', { name: '添加时间' }).click()
  await page.getByLabel('提醒时间 2', { exact: true }).fill('12:00')
  await page.getByRole('button', { name: '添加时间' }).click()
  await page.getByLabel('提醒时间 3', { exact: true }).fill('20:00')
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: '确认并保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.dose-row')).toHaveCount(3)
  await page.reload()
  await expect(page.locator('.dose-row')).toHaveCount(3)
  await page.getByRole('navigation', { name: '主导航' }).getByRole('button', { name: '我的药箱' }).click()
  await page.getByRole('button', { name: '查看 / 编辑' }).click()
  await page.getByLabel('药品规格').fill('编辑后的规格')
  await page.getByRole('button', { name: '设置提醒', exact: true }).click()
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: '确认并保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByText('编辑后的规格', { exact: true })).toBeVisible()
  await page.getByRole('navigation', { name: '主导航' }).getByRole('button', { name: '今日提醒' }).click()
  await page.locator('.dose-row').nth(0).getByRole('button', { name: '已服用', exact: true }).click()
  await page.getByRole('button', { name: '确认已服用', exact: true }).click()
  await expect(page.locator('.dose-row').nth(0).getByText('已服用', { exact: true })).toBeVisible()
  await page.locator('.dose-row').nth(1).getByRole('button', { name: '延后', exact: true }).click()
  await page.getByRole('button', { name: '确认延后', exact: true }).click()
  await expect(page.locator('.dose-row').nth(1).getByText('已延后', { exact: true })).toBeVisible()
  await page.locator('.dose-row').nth(2).getByRole('button', { name: '跳过', exact: true }).click()
  await page.getByRole('button', { name: '确认跳过', exact: true }).click()
  await expect(page.locator('.dose-row').nth(2).getByText('已跳过', { exact: true })).toBeVisible()
  await page.getByRole('navigation', { name: '主导航' }).getByRole('button', { name: '服药记录' }).click()
  await expect(page.locator('tbody tr')).toHaveCount(3)
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出记录' }).click()
  expect((await download).suggestedFilename()).toContain('服药记录')
  await page.getByRole('navigation', { name: '主导航' }).getByRole('button', { name: '我的药箱' }).click()
  await page.getByRole('button', { name: '归档界面验收药品' }).click()
  await page.getByRole('button', { name: '确认归档' }).click()
  await expect(page.getByText('你的药箱，等待第一份安心')).toBeVisible()
  await page.getByRole('button', { name: '退出登录' }).click()
  await expect(page.getByText('正在预览示例空间', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: '登录 / 注册', exact: true }).click()
  await page.getByLabel('邮箱地址').fill(email)
  await page.getByLabel('密码', { exact: true }).fill('test-password-2026')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('navigation', { name: '主导航' }).getByRole('button', { name: '服药记录' }).click()
  await expect(page.locator('tbody tr')).toHaveCount(3)
  expect(errors).toEqual([])
})

test('桌面、平板和手机布局及导航无横向溢出', async ({ page }) => {
  for (const width of [1440, 768, 390, 360]) {
    await page.setViewportSize({ width, height: 1000 })
    await page.goto('/')
    await expect(page.locator('.welcome-banner')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    if (width === 1440 || width === 390) await page.screenshot({ path: `docs/preview-${width}.png`, fullPage: true })
    const nav = page.getByRole('navigation', { name: width <= 760 ? '手机导航' : '主导航' })
    for (const label of ['我的药箱', '服药记录', '提醒设置']) {
      await nav.getByRole('button', { name: label, exact: true }).click()
      await expect(page.getByRole('heading', { level: 1 })).toContainText(label === '提醒设置' ? '提醒设置' : label)
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    }
    await page.getByRole('button', { name: '登录 / 注册', exact: true }).first().click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.getByRole('button', { name: '关闭弹窗' }).click()
  }
})

test('未配置 AI 时保留手动录入，上传图片可预览，非法图片显示错误', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '登录 / 注册', exact: true }).click()
  await page.getByRole('button', { name: '免费注册', exact: true }).click()
  await page.getByLabel('你的称呼').fill('图片测试')
  await page.getByLabel('邮箱地址').fill(`image-${Date.now()}@example.com`)
  await page.getByLabel('密码', { exact: true }).fill('test-password-2026')
  await page.getByRole('button', { name: '创建账户', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: '添加药品', exact: true }).click()
  await page.getByLabel('选择药品图片').setInputFiles('public/icon-192.png')
  await expect(page.getByAltText('待识别药品照片预览')).toBeVisible()
  await expect(page.getByRole('button', { name: 'AI 识别药品', exact: true })).toBeDisabled()
  await page.getByLabel('选择药品图片').setInputFiles({ name: 'invalid.txt', mimeType: 'text/plain', buffer: Buffer.from('test') })
  await expect(page.getByRole('alert')).toContainText('请选择 JPG')
  await page.getByRole('button', { name: '手动填写' }).click()
  await expect(page.getByLabel('药品名称')).toBeVisible()
})

test('手机端：AI 结果先确认再保存，原始照片不进入药箱，账户可退出', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  // This is an explicit transport stub. It tests UI wiring, not real recognition accuracy.
  await page.route('**/api/config', route => route.fulfill({ json: { data: { aiEnabled: true, pushEnabled: false, vapidPublicKey: '' } } }))
  let imageWasSent = false
  await page.route('**/api/recognize', route => {
    imageWasSent = route.request().postDataJSON().image.startsWith('data:image/png;base64,')
    return route.fulfill({ json: { data: { name: '模拟识别药品', specification: '20mg × 12片', expiryDate: '', instructions: '模拟包装文字，仅用于接线测试。', warnings: ['有效期无法确认，请核对包装。'] } } })
  })
  await page.goto('/')
  await page.getByRole('button', { name: '登录 / 注册', exact: true }).click()
  await page.getByRole('button', { name: '免费注册', exact: true }).click()
  await page.getByLabel('你的称呼').fill('手机用户')
  await page.getByLabel('邮箱地址').fill(`mobile-${Date.now()}@example.com`)
  await page.getByLabel('密码', { exact: true }).fill('test-password-2026')
  await page.getByRole('button', { name: '创建账户', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: '添加药品', exact: true }).click()
  await page.getByLabel('选择药品图片').setInputFiles('public/icon-192.png')
  await page.getByRole('button', { name: 'AI 识别药品', exact: true }).click()
  await expect(page.getByLabel('药品名称')).toHaveValue('模拟识别药品')
  expect(imageWasSent).toBe(true)
  expect((await (await page.request.get('/api/medications')).json()).data).toHaveLength(0)
  await page.getByLabel('药品名称').fill('用户核对后的药品')
  await page.getByLabel('有效期至').fill('2030-01-01')
  await page.getByRole('button', { name: '设置提醒', exact: true }).click()
  await expect(page.getByLabel('每次用量')).toBeEmpty()
  await page.getByLabel('每次用量').fill('仅测试：1片')
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: '确认并保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const meds = (await (await page.request.get('/api/medications')).json()).data
  expect(meds).toHaveLength(1)
  expect(meds[0].name).toBe('用户核对后的药品')
  expect(meds[0].image).toBeUndefined()
  await page.getByRole('navigation', { name: '手机导航' }).getByRole('button', { name: '提醒设置' }).click()
  await page.getByRole('button', { name: '退出账户' }).click()
  await expect(page.getByText('正在预览示例空间', { exact: false })).toBeVisible()
})
